# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\screen.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(380, 595)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(5, -1, 5, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMinimumSize(QtCore.QSize(0, 30))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMinimumSize(QtCore.QSize(0, 30))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.edtFile = QtWidgets.QLineEdit(self.centralwidget)
        self.edtFile.setMinimumSize(QtCore.QSize(0, 30))
        self.edtFile.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.edtFile.setFont(font)
        self.edtFile.setReadOnly(True)
        self.edtFile.setObjectName("edtFile")
        self.horizontalLayout.addWidget(self.edtFile)
        self.btnSelectFile = QtWidgets.QPushButton(self.centralwidget)
        self.btnSelectFile.setMinimumSize(QtCore.QSize(30, 30))
        self.btnSelectFile.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnSelectFile.setFont(font)
        self.btnSelectFile.setObjectName("btnSelectFile")
        self.horizontalLayout.addWidget(self.btnSelectFile)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.cmbSheet = QtWidgets.QComboBox(self.centralwidget)
        self.cmbSheet.setMinimumSize(QtCore.QSize(0, 30))
        self.cmbSheet.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cmbSheet.setFont(font)
        self.cmbSheet.setObjectName("cmbSheet")
        self.verticalLayout_2.addWidget(self.cmbSheet)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.spbCountryCode = QtWidgets.QSpinBox(self.centralwidget)
        self.spbCountryCode.setMinimumSize(QtCore.QSize(0, 30))
        self.spbCountryCode.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spbCountryCode.setFont(font)
        self.spbCountryCode.setMinimum(1)
        self.spbCountryCode.setMaximum(9999)
        self.spbCountryCode.setProperty("value", 33)
        self.spbCountryCode.setObjectName("spbCountryCode")
        self.horizontalLayout_5.addWidget(self.spbCountryCode)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMinimumSize(QtCore.QSize(0, 30))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.spbPhone = QtWidgets.QSpinBox(self.centralwidget)
        self.spbPhone.setMinimumSize(QtCore.QSize(0, 30))
        self.spbPhone.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spbPhone.setFont(font)
        self.spbPhone.setMinimum(1)
        self.spbPhone.setProperty("value", 5)
        self.spbPhone.setObjectName("spbPhone")
        self.horizontalLayout_5.addWidget(self.spbPhone)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_5.setStretch(4, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.edtMsgCols = QtWidgets.QLineEdit(self.centralwidget)
        self.edtMsgCols.setMinimumSize(QtCore.QSize(0, 30))
        self.edtMsgCols.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.edtMsgCols.setFont(font)
        self.edtMsgCols.setInputMask("")
        self.edtMsgCols.setObjectName("edtMsgCols")
        self.verticalLayout_2.addWidget(self.edtMsgCols)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.edtMsgImg = QtWidgets.QLineEdit(self.centralwidget)
        self.edtMsgImg.setMinimumSize(QtCore.QSize(0, 30))
        self.edtMsgImg.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.edtMsgImg.setFont(font)
        self.edtMsgImg.setReadOnly(True)
        self.edtMsgImg.setObjectName("edtMsgImg")
        self.horizontalLayout_6.addWidget(self.edtMsgImg)
        self.btnSelectImgs = QtWidgets.QPushButton(self.centralwidget)
        self.btnSelectImgs.setMinimumSize(QtCore.QSize(30, 30))
        self.btnSelectImgs.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnSelectImgs.setFont(font)
        self.btnSelectImgs.setObjectName("btnSelectImgs")
        self.horizontalLayout_6.addWidget(self.btnSelectImgs)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.btnStart = QtWidgets.QPushButton(self.centralwidget)
        self.btnStart.setMinimumSize(QtCore.QSize(0, 30))
        self.btnStart.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnStart.setFont(font)
        self.btnStart.setObjectName("btnStart")
        self.horizontalLayout_4.addWidget(self.btnStart)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.lstHistory = QtWidgets.QListView(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lstHistory.setFont(font)
        self.lstHistory.setObjectName("lstHistory")
        self.verticalLayout_3.addWidget(self.lstHistory)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Excel File"))
        self.label_2.setText(_translate("MainWindow", "Sheet"))
        self.label_3.setText(_translate("MainWindow", "Country code"))
        self.label_5.setText(_translate("MainWindow", "Msg Cols"))
        self.label_4.setText(_translate("MainWindow", "Send Image"))
        self.edtFile.setPlaceholderText(_translate("MainWindow", "Your excel file path"))
        self.btnSelectFile.setText(_translate("MainWindow", "..."))
        self.label_7.setText(_translate("MainWindow", "+"))
        self.label_6.setText(_translate("MainWindow", "Phone col"))
        self.edtMsgCols.setPlaceholderText(_translate("MainWindow", "Hello[6]msg2[col2]msg3[col3]"))
        self.edtMsgImg.setPlaceholderText(_translate("MainWindow", "Image file path"))
        self.btnSelectImgs.setText(_translate("MainWindow", "..."))
        self.btnStart.setText(_translate("MainWindow", "Start"))
